#import "template.typ": card-do, card-dont

= Extended Reference Schedules and Indices

This chapter gathers orientation tables that employees and reviewers use to navigate the handbook. It is a finding aid, not a fresh source of rules.

#card-dont("Treat these orientation tables as binding")[
  Every table in this chapter summarizes material stated elsewhere. Where a table here is incomplete, out of date, or differs in any way from Chapter 6, Chapter 7, Chapter 9, or the Appendix of Chapter 14, those authoritative chapters govern. Version 4.2 governs every claim processed on or after January 1, 2024, regardless of the date printed on a receipt.
]

== Metropolitan Market Tier Index

#table(
  columns: (1.4fr, 1.4fr, 1fr, 1.4fr),
  align: (left, left, center, center),
  fill: (_, y) => if y == 0 { rgb("#dbeafe") } else if calc.even(y) { rgb("#f8fafc") } else { none },
  stroke: 0.5pt + rgb("#cbd5e1"),
  table.header[*Metropolitan Market*][*Country*][*Assigned Tier*][*Binding Schedule*],
  [London], [United Kingdom], [Tier 1], [Chapter 14 binds], 
  [New York City], [United States], [Tier 1], [Chapter 14 binds], 
  [San Francisco], [United States], [Tier 1], [Chapter 14 binds], 
  [Zurich], [Switzerland], [Tier 1], [Chapter 14 binds], 
  [Geneva], [Switzerland], [Tier 1], [Chapter 14 binds], 
  [Paris], [France], [Tier 1], [Chapter 14 binds], 
  [Tokyo], [Japan], [Tier 1], [Chapter 14 binds], 
  [Singapore], [Singapore], [Tier 1], [Chapter 14 binds], 
  [Hong Kong], [Hong Kong SAR], [Tier 1], [Chapter 14 binds], 
  [Berlin], [Germany], [Tier 2], [Chapter 14 binds], 
  [Munich], [Germany], [Tier 2], [Chapter 14 binds], 
  [Frankfurt], [Germany], [Tier 2], [Chapter 14 binds], 
  [Hamburg], [Germany], [Tier 2], [Chapter 14 binds], 
  [Amsterdam], [Netherlands], [Tier 2], [Chapter 14 binds], 
  [Dublin], [Ireland], [Tier 2], [Chapter 14 binds], 
  [Chicago], [United States], [Tier 2], [Chapter 14 binds], 
  [Boston], [United States], [Tier 2], [Chapter 14 binds], 
  [Seattle], [United States], [Tier 2], [Chapter 14 binds], 
  [Toronto], [Canada], [Tier 2], [Chapter 14 binds], 
  [Sydney], [Australia], [Tier 2], [Chapter 14 binds], 
  [Milan], [Italy], [Tier 2], [Chapter 14 binds], 
  [Leipzig], [Germany], [Tier 3], [Chapter 14 binds], 
  [Düsseldorf], [Germany], [Tier 3], [Chapter 14 binds], 
  [Dortmund], [Germany], [Tier 3], [Chapter 14 binds], 
  [Köln], [Germany], [Tier 3], [Chapter 14 binds], 
  [Darmstadt], [Germany], [Tier 3], [Chapter 14 binds], 
  [Stuttgart], [Germany], [Tier 3], [Chapter 14 binds], 
  [Nuremberg], [Germany], [Tier 3], [Chapter 14 binds], 
  [Bonn], [Germany], [Tier 3], [Chapter 14 binds], 
  [Essen], [Germany], [Tier 3], [Chapter 14 binds], 
  [Bremen], [Germany], [Tier 3], [Chapter 14 binds], 
  [Hanover], [Germany], [Tier 3], [Chapter 14 binds], 
  [Dresden], [Germany], [Tier 3], [Chapter 14 binds], 
  [Freiburg], [Germany], [Tier 3], [Chapter 14 binds], 
  [Mannheim], [Germany], [Tier 3], [Chapter 14 binds], 
  [Karlsruhe], [Germany], [Tier 3], [Chapter 14 binds], 
  [Münster], [Germany], [Tier 3], [Chapter 14 binds], 
  [Wiesbaden], [Germany], [Tier 3], [Chapter 14 binds], 
  [Augsburg], [Germany], [Tier 3], [Chapter 14 binds], 
  [Kiel], [Germany], [Tier 3], [Chapter 14 binds], 
  [Vienna], [Austria], [Tier 3], [Chapter 14 binds], 
  [Salzburg], [Austria], [Tier 3], [Chapter 14 binds], 
  [Graz], [Austria], [Tier 3], [Chapter 14 binds], 
  [Linz], [Austria], [Tier 3], [Chapter 14 binds], 
  [Basel], [Switzerland], [Tier 3], [Chapter 14 binds], 
  [Bern], [Switzerland], [Tier 3], [Chapter 14 binds], 
  [Lausanne], [Switzerland], [Tier 3], [Chapter 14 binds], 
  [Brussels], [Belgium], [Tier 3], [Chapter 14 binds], 
  [Antwerp], [Belgium], [Tier 3], [Chapter 14 binds], 
  [Ghent], [Belgium], [Tier 3], [Chapter 14 binds], 
  [Leuven], [Belgium], [Tier 3], [Chapter 14 binds], 
  [Rotterdam], [Netherlands], [Tier 3], [Chapter 14 binds], 
  [The Hague], [Netherlands], [Tier 3], [Chapter 14 binds], 
  [Utrecht], [Netherlands], [Tier 3], [Chapter 14 binds], 
  [Eindhoven], [Netherlands], [Tier 3], [Chapter 14 binds], 
  [Copenhagen], [Denmark], [Tier 3], [Chapter 14 binds], 
  [Aarhus], [Denmark], [Tier 3], [Chapter 14 binds], 
  [Oslo], [Norway], [Tier 3], [Chapter 14 binds], 
  [Bergen], [Norway], [Tier 3], [Chapter 14 binds], 
  [Stockholm], [Sweden], [Tier 3], [Chapter 14 binds], 
  [Gothenburg], [Sweden], [Tier 3], [Chapter 14 binds], 
  [Malmo], [Sweden], [Tier 3], [Chapter 14 binds], 
  [Helsinki], [Finland], [Tier 3], [Chapter 14 binds], 
  [Espoo], [Finland], [Tier 3], [Chapter 14 binds], 
  [Tampere], [Finland], [Tier 3], [Chapter 14 binds], 
  [Madrid], [Spain], [Tier 3], [Chapter 14 binds], 
  [Barcelona], [Spain], [Tier 3], [Chapter 14 binds], 
  [Valencia], [Spain], [Tier 3], [Chapter 14 binds], 
  [Seville], [Spain], [Tier 3], [Chapter 14 binds], 
  [Bilbao], [Spain], [Tier 3], [Chapter 14 binds], 
  [Lisbon], [Portugal], [Tier 3], [Chapter 14 binds], 
  [Porto], [Portugal], [Tier 3], [Chapter 14 binds], 
  [Rome], [Italy], [Tier 3], [Chapter 14 binds], 
  [Turin], [Italy], [Tier 3], [Chapter 14 binds], 
  [Florence], [Italy], [Tier 3], [Chapter 14 binds], 
  [Naples], [Italy], [Tier 3], [Chapter 14 binds], 
  [Bologna], [Italy], [Tier 3], [Chapter 14 binds], 
  [Venice], [Italy], [Tier 3], [Chapter 14 binds], 
  [Athens], [Greece], [Tier 3], [Chapter 14 binds], 
  [Thessaloniki], [Greece], [Tier 3], [Chapter 14 binds], 
  [Prague], [Czechia], [Tier 3], [Chapter 14 binds], 
  [Brno], [Czechia], [Tier 3], [Chapter 14 binds], 
  [Warsaw], [Poland], [Tier 3], [Chapter 14 binds], 
  [Krakow], [Poland], [Tier 3], [Chapter 14 binds], 
  [Wroclaw], [Poland], [Tier 3], [Chapter 14 binds], 
  [Budapest], [Hungary], [Tier 3], [Chapter 14 binds], 
  [Bucharest], [Romania], [Tier 3], [Chapter 14 binds], 
  [Sofia], [Bulgaria], [Tier 3], [Chapter 14 binds], 
  [Belgrade], [Serbia], [Tier 3], [Chapter 14 binds], 
  [Zagreb], [Croatia], [Tier 3], [Chapter 14 binds], 
  [Bratislava], [Slovakia], [Tier 3], [Chapter 14 binds], 
  [Ljubljana], [Slovenia], [Tier 3], [Chapter 14 binds], 
  [Riga], [Latvia], [Tier 3], [Chapter 14 binds], 
  [Tallinn], [Estonia], [Tier 3], [Chapter 14 binds], 
  [Vilnius], [Lithuania], [Tier 3], [Chapter 14 binds], 
  [Tel Aviv], [Israel], [Tier 3], [Chapter 14 binds], 
  [Jerusalem], [Israel], [Tier 3], [Chapter 14 binds], 
  [Haifa], [Israel], [Tier 3], [Chapter 14 binds], 
  [Dubai], [United Arab Emirates], [Tier 3], [Chapter 14 binds], 
  [Abu Dhabi], [United Arab Emirates], [Tier 3], [Chapter 14 binds], 
  [Doha], [Qatar], [Tier 3], [Chapter 14 binds], 
  [Riyadh], [Saudi Arabia], [Tier 3], [Chapter 14 binds], 
  [Kuwait City], [Kuwait], [Tier 3], [Chapter 14 binds], 
  [Manama], [Bahrain], [Tier 3], [Chapter 14 binds], 
  [Muscat], [Oman], [Tier 3], [Chapter 14 binds], 
  [Istanbul], [Turkey], [Tier 3], [Chapter 14 binds], 
  [Ankara], [Turkey], [Tier 3], [Chapter 14 binds], 
  [Cairo], [Egypt], [Tier 3], [Chapter 14 binds], 
  [Nairobi], [Kenya], [Tier 3], [Chapter 14 binds], 
  [Lagos], [Nigeria], [Tier 3], [Chapter 14 binds], 
  [Johannesburg], [South Africa], [Tier 3], [Chapter 14 binds], 
  [Cape Town], [South Africa], [Tier 3], [Chapter 14 binds], 
  [Casablanca], [Morocco], [Tier 3], [Chapter 14 binds], 
  [Mumbai], [India], [Tier 3], [Chapter 14 binds], 
  [New Delhi], [India], [Tier 3], [Chapter 14 binds], 
  [Bengaluru], [India], [Tier 3], [Chapter 14 binds], 
  [Chennai], [India], [Tier 3], [Chapter 14 binds], 
  [Pune], [India], [Tier 3], [Chapter 14 binds], 
  [Hyderabad], [India], [Tier 3], [Chapter 14 binds], 
  [Bangkok], [Thailand], [Tier 3], [Chapter 14 binds], 
  [Jakarta], [Indonesia], [Tier 3], [Chapter 14 binds], 
  [Manila], [Philippines], [Tier 3], [Chapter 14 binds], 
  [Ho Chi Minh City], [Vietnam], [Tier 3], [Chapter 14 binds], 
  [Hanoi], [Vietnam], [Tier 3], [Chapter 14 binds], 
  [Kuala Lumpur], [Malaysia], [Tier 3], [Chapter 14 binds], 
  [Taipei], [Taiwan], [Tier 3], [Chapter 14 binds], 
  [Seoul], [South Korea], [Tier 3], [Chapter 14 binds], 
  [Busan], [South Korea], [Tier 3], [Chapter 14 binds], 
  [Brisbane], [Australia], [Tier 3], [Chapter 14 binds], 
  [Melbourne], [Australia], [Tier 3], [Chapter 14 binds], 
  [Perth], [Australia], [Tier 3], [Chapter 14 binds], 
  [Auckland], [New Zealand], [Tier 3], [Chapter 14 binds], 
  [Wellington], [New Zealand], [Tier 3], [Chapter 14 binds], 
  [Vancouver], [Canada], [Tier 3], [Chapter 14 binds], 
  [Montreal], [Canada], [Tier 3], [Chapter 14 binds], 
  [Calgary], [Canada], [Tier 3], [Chapter 14 binds], 
  [Ottawa], [Canada], [Tier 3], [Chapter 14 binds], 
  [Mexico City], [Mexico], [Tier 3], [Chapter 14 binds], 
  [Monterrey], [Mexico], [Tier 3], [Chapter 14 binds], 
  [Sao Paulo], [Brazil], [Tier 3], [Chapter 14 binds], 
  [Rio de Janeiro], [Brazil], [Tier 3], [Chapter 14 binds], 
  [Buenos Aires], [Argentina], [Tier 3], [Chapter 14 binds], 
  [Santiago], [Chile], [Tier 3], [Chapter 14 binds], 
  [Lima], [Peru], [Tier 3], [Chapter 14 binds], 
  [Bogota], [Colombia], [Tier 3], [Chapter 14 binds], 
  [Atlanta], [United States], [Tier 3], [Chapter 14 binds], 
  [Miami], [United States], [Tier 3], [Chapter 14 binds], 
  [Dallas], [United States], [Tier 3], [Chapter 14 binds], 
  [Houston], [United States], [Tier 3], [Chapter 14 binds], 
  [Denver], [United States], [Tier 3], [Chapter 14 binds], 
  [Phoenix], [United States], [Tier 3], [Chapter 14 binds], 
  [Los Angeles], [United States], [Tier 3], [Chapter 14 binds], 
  [San Diego], [United States], [Tier 3], [Chapter 14 binds], 
  [Portland], [United States], [Tier 3], [Chapter 14 binds], 
  [Austin], [United States], [Tier 3], [Chapter 14 binds], 
  [Nashville], [United States], [Tier 3], [Chapter 14 binds], 
  [Philadelphia], [United States], [Tier 3], [Chapter 14 binds], 
  [Washington DC], [United States], [Tier 3], [Chapter 14 binds], 
  [New Orleans], [United States], [Tier 3], [Chapter 14 binds], 
  [Minneapolis], [United States], [Tier 3], [Chapter 14 binds], 
  [Detroit], [United States], [Tier 3], [Chapter 14 binds], 
  [Charlotte], [United States], [Tier 3], [Chapter 14 binds], 
  [Pittsburgh], [United States], [Tier 3], [Chapter 14 binds], 
  [Cleveland], [United States], [Tier 3], [Chapter 14 binds], 
  [Columbus], [United States], [Tier 3], [Chapter 14 binds], 
  [Indianapolis], [United States], [Tier 3], [Chapter 14 binds], 
  [Kansas City], [United States], [Tier 3], [Chapter 14 binds], 
  [Salt Lake City], [United States], [Tier 3], [Chapter 14 binds], 
  [St. Louis], [United States], [Tier 3], [Chapter 14 binds], 
  [Raleigh], [United States], [Tier 3], [Chapter 14 binds], 
  [Richmond], [United States], [Tier 3], [Chapter 14 binds], 
  [Orlando], [United States], [Tier 3], [Chapter 14 binds], 
  [Tampa], [United States], [Tier 3], [Chapter 14 binds], 
)

== Country, Region, and Currency Orientation

#table(
  columns: (1.6fr, 1.2fr, 1.6fr, 1fr),
  align: (left, left, center, center),
  fill: (_, y) => if y == 0 { rgb("#dbeafe") } else if calc.even(y) { rgb("#f8fafc") } else { none },
  stroke: 0.5pt + rgb("#cbd5e1"),
  table.header[*Country*][*Region*][*Tipping Status*][*Currency*],
  [United States], [—], [Chapter 14 binds], [—], 
  [Canada], [—], [Chapter 14 binds], [—], 
  [Germany], [—], [Chapter 14 binds], [—], 
  [United Kingdom], [—], [Chapter 14 binds], [—], 
  [Austria], [—], [Chapter 14 binds], [—], 
  [Belgium], [—], [Chapter 14 binds], [—], 
  [Bulgaria], [—], [Chapter 14 binds], [—], 
  [Croatia], [—], [Chapter 14 binds], [—], 
  [Cyprus], [—], [Chapter 14 binds], [—], 
  [Czechia], [—], [Chapter 14 binds], [—], 
  [Denmark], [—], [Chapter 14 binds], [—], 
  [Estonia], [—], [Chapter 14 binds], [—], 
  [Finland], [—], [Chapter 14 binds], [—], 
  [France], [—], [Chapter 14 binds], [—], 
  [Greece], [—], [Chapter 14 binds], [—], 
  [Hungary], [—], [Chapter 14 binds], [—], 
  [Iceland], [—], [Chapter 14 binds], [—], 
  [Ireland], [—], [Chapter 14 binds], [—], 
  [Italy], [—], [Chapter 14 binds], [—], 
  [Latvia], [—], [Chapter 14 binds], [—], 
  [Liechtenstein], [—], [Chapter 14 binds], [—], 
  [Lithuania], [—], [Chapter 14 binds], [—], 
  [Luxembourg], [—], [Chapter 14 binds], [—], 
  [Malta], [—], [Chapter 14 binds], [—], 
  [Netherlands], [—], [Chapter 14 binds], [—], 
  [Norway], [—], [Chapter 14 binds], [—], 
  [Poland], [—], [Chapter 14 binds], [—], 
  [Portugal], [—], [Chapter 14 binds], [—], 
  [Romania], [—], [Chapter 14 binds], [—], 
  [Slovakia], [—], [Chapter 14 binds], [—], 
  [Slovenia], [—], [Chapter 14 binds], [—], 
  [Spain], [—], [Chapter 14 binds], [—], 
  [Sweden], [—], [Chapter 14 binds], [—], 
  [Switzerland], [—], [Chapter 14 binds], [—], 
  [Japan], [—], [Chapter 14 binds], [—], 
  [South Korea], [—], [Chapter 14 binds], [—], 
  [Singapore], [—], [Chapter 14 binds], [—], 
  [Hong Kong], [—], [Chapter 14 binds], [—], 
  [Australia], [Asia-Pacific], [Chapter 14 binds], [AUD], 
  [New Zealand], [Asia-Pacific], [Chapter 14 binds], [NZD], 
  [China], [Asia-Pacific], [Chapter 14 binds], [CNY], 
  [Taiwan], [Asia-Pacific], [Chapter 14 binds], [TWD], 
  [India], [Asia-Pacific], [Chapter 14 binds], [INR], 
  [Indonesia], [Asia-Pacific], [Chapter 14 binds], [IDR], 
  [Malaysia], [Asia-Pacific], [Chapter 14 binds], [MYR], 
  [Thailand], [Asia-Pacific], [Chapter 14 binds], [THB], 
  [Vietnam], [Asia-Pacific], [Chapter 14 binds], [VND], 
  [Philippines], [Asia-Pacific], [Chapter 14 binds], [PHP], 
  [United Arab Emirates], [Middle East], [Chapter 14 binds], [AED], 
  [Saudi Arabia], [Middle East], [Chapter 14 binds], [SAR], 
  [Qatar], [Middle East], [Chapter 14 binds], [QAR], 
  [Israel], [Middle East], [Chapter 14 binds], [ILS], 
  [Turkey], [Middle East], [Chapter 14 binds], [TRY], 
  [Egypt], [Africa], [Chapter 14 binds], [EGP], 
  [South Africa], [Africa], [Chapter 14 binds], [ZAR], 
  [Kenya], [Africa], [Chapter 14 binds], [KES], 
  [Nigeria], [Africa], [Chapter 14 binds], [NGN], 
  [Morocco], [Africa], [Chapter 14 binds], [MAD], 
  [Brazil], [Latin America], [Chapter 14 binds], [BRL], 
  [Mexico], [Latin America], [Chapter 14 binds], [MXN], 
  [Argentina], [Latin America], [Chapter 14 binds], [ARS], 
  [Chile], [Latin America], [Chapter 14 binds], [CLP], 
  [Colombia], [Latin America], [Chapter 14 binds], [COP], 
  [Peru], [Latin America], [Chapter 14 binds], [PEN], 
)

== Master Item Keyword Index

This index maps receipt wording to the chapter that governs it. It records where a rule lives, not what the rule decides; the governing chapter always supplies the conditions.

#table(
  columns: (2.2fr, 1.2fr, 2.6fr, 1fr),
  align: (left, left, left, center),
  fill: (_, y) => if y == 0 { rgb("#dbeafe") } else if calc.even(y) { rgb("#f8fafc") } else { none },
  stroke: 0.5pt + rgb("#cbd5e1"),
  table.header[*Item or Keyword*][*Category*][*Governing Reference*][*Chapter*],
  [Airline base fare], [Air travel], [Chapter 4 governs], [4], 
  [Economy cabin], [Air travel], [Chapter 4 governs], [4], 
  [Premium economy cabin], [Air travel], [Chapter 4 governs], [4], 
  [Business class on short-haul], [Air travel], [Chapter 4 governs], [4], 
  [First class cabin], [Air travel], [Chapter 4 governs], [4], 
  [Airport passenger service charge], [Air travel], [Chapter 4 governs], [4], 
  [Aviation security charge], [Air travel], [Chapter 4 governs], [4], 
  [Carrier-imposed fuel surcharge], [Air travel], [Chapter 4 governs], [4], 
  [Government departure tax], [Air travel], [Chapter 4 governs], [4], 
  [Seat selection fee], [Air travel], [Chapter 4 governs], [4], 
  [Extra-legroom seat], [Air travel], [Chapter 4 governs], [4], 
  [Priority boarding], [Air travel], [Chapter 4 governs], [4], 
  [Airport lounge day pass], [Air travel], [Chapter 4 governs], [4], 
  [Checked baggage fee], [Air travel], [Chapter 4 governs], [4], 
  [In-flight Wi-Fi], [Air travel], [Chapter 4 governs], [4], 
  [Flight change fee], [Air travel], [Chapter 4 governs], [4], 
  [Unused non-refundable ticket], [Air travel], [Chapter 4 governs], [4], 
  [Rail second class fare], [Ground transport], [Chapter 5 governs], [5], 
  [Rail first class fare], [Ground transport], [Chapter 5 governs], [5], 
  [Seat reservation fee], [Ground transport], [Chapter 5 governs], [5], 
  [Flexible rail fare], [Ground transport], [Chapter 5 governs], [5], 
  [Rail season pass], [Ground transport], [Chapter 5 governs], [5], 
  [Taxi or ride-hailing fare], [Ground transport], [Chapter 5 governs], [5], 
  [Premium rideshare tier], [Ground transport], [Chapter 5 governs], [5], 
  [Taxi waiting time], [Ground transport], [Chapter 5 governs], [5], 
  [Taxi luggage surcharge], [Ground transport], [Chapter 5 governs], [5], 
  [Rental car, intermediate], [Ground transport], [Chapter 5 governs], [5], 
  [Rental car, premium], [Ground transport], [Chapter 5 governs], [5], 
  [Rental collision damage waiver], [Ground transport], [Chapter 5 governs], [5], 
  [Fuel for rental vehicle], [Ground transport], [Chapter 5 governs], [5], 
  [Mileage, personal vehicle], [Ground transport], [Chapter 5 governs], [5], 
  [Road toll], [Ground transport], [Chapter 5 governs], [5], 
  [Congestion charge], [Ground transport], [Chapter 5 governs], [5], 
  [Parking garage fee], [Ground transport], [Chapter 5 governs], [5], 
  [Parking fine], [Ground transport], [Chapter 11 governs], [11], 
  [Commuting fare], [Ground transport], [Chapter 11 governs], [11], 
  [Hotel room rate], [Lodging], [Chapter 6 governs], [6], 
  [Hotel suite upgrade], [Lodging], [Chapter 6 governs], [6], 
  [Hotel city tax], [Lodging], [Chapter 6 governs], [6], 
  [Resort or facility fee], [Lodging], [Chapter 6 governs], [6], 
  [Optional amenity bundle], [Lodging], [Chapter 6 governs], [6], 
  [Hotel minibar item], [Lodging], [Chapter 6 governs], [6], 
  [Pay-per-view movie], [Lodging], [Chapter 6 governs], [6], 
  [Spa or massage treatment], [Lodging], [Chapter 6 governs], [6], 
  [Hotel gym surcharge], [Lodging], [Chapter 6 governs], [6], 
  [Pet cleaning fee], [Lodging], [Chapter 6 governs], [6], 
  [Late check-out fee], [Lodging], [Chapter 6 governs], [6], 
  [Laundry on a stay over five nights], [Lodging], [Chapter 6 governs], [6], 
  [Garment rescue on a short stay], [Lodging], [Chapter 6 governs], [6], 
  [Hotel parking with rental vehicle], [Lodging], [Chapter 6 governs], [6], 
  [Hotel breakfast line], [Lodging], [Chapter 6 governs], [6], 
  [Room service dinner], [Lodging], [Chapter 6 governs], [6], 
  [Breakfast (solo)], [Meals], [Chapter 7 governs], [7], 
  [Lunch (solo)], [Meals], [Chapter 7 governs], [7], 
  [Dinner (solo)], [Meals], [Chapter 7 governs], [7], 
  [Daily food total (solo)], [Meals], [Chapter 7 governs], [7], 
  [Overtime meal at home office], [Meals], [Chapter 7 governs], [7], 
  [Alcohol (solo travel)], [Meals], [Chapter 7 governs], [7], 
  [Non-alcoholic beer or mocktail], [Meals], [Chapter 7 governs], [7], 
  [Restaurant service charge], [Meals], [Chapter 7 governs], [7], 
  [Restaurant tip], [Meals], [Chapter 7 governs], [7], 
  [Truffle dish], [Meals], [Chapter 13 governs], [13], 
  [Truffle oil], [Meals], [Chapter 13 governs], [13], 
  [Caviar], [Meals], [Chapter 7 governs], [7], 
  [Wagyu dish], [Meals], [Chapter 7 governs], [7], 
  [Lobster dish], [Meals], [Chapter 7 governs], [7], 
  [Client dinner food], [Client hospitality], [Chapter 13 governs], [13], 
  [Client dinner alcohol], [Client hospitality], [Chapter 13 governs], [13], 
  [Internal team meal], [Client hospitality], [Chapter 13 governs], [13], 
  [Candidate interview meal], [Client hospitality], [Chapter 8 governs], [8], 
  [Sports event ticket], [Client hospitality], [Chapter 8 governs], [8], 
  [Theater ticket], [Client hospitality], [Chapter 8 governs], [8], 
  [VIP hospitality box], [Client hospitality], [Chapter 8 governs], [8], 
  [Night club bill], [Client hospitality], [Chapter 8 governs], [8], 
  [Casino bill], [Client hospitality], [Chapter 8 governs], [8], 
  [Weekend restaurant receipt], [Weekend], [Chapter 13 governs], [13], 
  [Weekend hotel night], [Weekend], [Chapter 13 governs], [13], 
  [Weekend taxi receipt], [Weekend], [Chapter 13 governs], [13], 
  [Personal extension hotel night], [Weekend], [Chapter 9 governs], [9], 
  [Museum admission], [Weekend], [Chapter 9 governs], [9], 
  [City tour ticket], [Weekend], [Chapter 9 governs], [9], 
  [Companion airfare], [Companions], [Chapter 11 governs], [11], 
  [Companion meal share], [Companions], [Chapter 9 governs], [9], 
  [Double-occupancy surcharge], [Companions], [Chapter 9 governs], [9], 
  [Stationery under the cap], [Equipment], [Chapter 10 governs], [10], 
  [Bulk paper order], [Equipment], [Chapter 10 governs], [10], 
  [Peripheral under the threshold], [Equipment], [Chapter 10 governs], [10], 
  [Peripheral at or above threshold], [Equipment], [Chapter 10 governs], [10], 
  [Replacement charger while traveling], [Equipment], [Chapter 10 governs], [10], 
  [External monitor], [Equipment], [Chapter 10 governs], [10], 
  [Noise-canceling headset], [Equipment], [Chapter 10 governs], [10], 
  [Specialist test equipment], [Equipment], [Chapter 10 governs], [10], 
  [Office chair or standing desk], [Equipment], [Chapter 10 governs], [10], 
  [Office plant or plant care], [Equipment], [Chapter 10 governs], [10], 
  [Temporary event staging greenery], [Equipment], [Chapter 10 governs], [10], 
  [Software subscription], [Equipment], [Chapter 10 governs], [10], 
  [Cloud compute credits], [Equipment], [Chapter 10 governs], [10], 
  [Generative AI API credits], [Equipment], [Chapter 10 governs], [10], 
  [Event booth display], [Equipment], [Chapter 10 governs], [10], 
  [Promotional giveaway], [Equipment], [Chapter 10 governs], [10], 
  [Team swag], [Equipment], [Chapter 10 governs], [10], 
  [Workshop prop], [Equipment], [Chapter 10 governs], [10], 
  [Team-building activity], [Equipment], [Chapter 10 governs], [10], 
  [Courier of client deliverables], [Equipment], [Chapter 10 governs], [10], 
  [Travel eSIM or data bundle], [Equipment], [Chapter 10 governs], [10], 
  [Professional book], [Equipment], [Chapter 10 governs], [10], 
  [Professional periodical], [Equipment], [Chapter 10 governs], [10], 
  [Retail gift card], [Prohibited], [Chapter 11 governs], [11], 
  [Amazon voucher], [Prohibited], [Chapter 11 governs], [11], 
  [Prepaid debit card], [Prohibited], [Chapter 11 governs], [11], 
  [Traffic citation], [Prohibited], [Chapter 11 governs], [11], 
  [Haircut or salon], [Prohibited], [Chapter 11 governs], [11], 
  [Personal clothing], [Prohibited], [Chapter 11 governs], [11], 
  [Over-the-counter medicine], [Prohibited], [Chapter 11 governs], [11], 
  [Gym day pass], [Prohibited], [Chapter 11 governs], [11], 
  [Sunscreen], [Prohibited], [Chapter 11 governs], [11], 
  [Luggage set], [Prohibited], [Chapter 11 governs], [11], 
  [Passport renewal fee], [Prohibited], [Chapter 11 governs], [11], 
  [Tourist visa fee], [Prohibited], [Chapter 11 governs], [11], 
  [Neck pillow], [Prohibited], [Chapter 11 governs], [11], 
  [Streaming subscription], [Prohibited], [Chapter 11 governs], [11], 
  [Pet boarding], [Prohibited], [Chapter 11 governs], [11], 
  [Childcare during travel], [Prohibited], [Chapter 11 governs], [11], 
  [Lost-baggage essentials], [Exception], [Chapter 11 governs], [11], 
  [VAT on a commercial invoice], [Tax], [Chapter 12 governs], [12], 
  [VAT on a folio missing its number], [Tax], [Chapter 12 governs], [12], 
  [Foreign cash left over], [Tax], [Chapter 12 governs], [12], 
  [Dynamic currency conversion markup], [Tax], [Chapter 12 governs], [12], 
)

== Terminology

#table(
  columns: (1.4fr, 4fr, 1.6fr),
  align: (left, left, left),
  fill: (_, y) => if y == 0 { rgb("#dbeafe") } else if calc.even(y) { rgb("#f8fafc") } else { none },
  stroke: 0.5pt + rgb("#cbd5e1"),
  table.header[*Term*][*Meaning*][*Status*],
  [Aggregate cap], [The maximum a category may reimburse across a day or period.], [Governing chapter binds], 
  [Approving manager], [The person with Delegation of Authority for a claim's value.], [Governing chapter binds], 
  [Bleisure], [Personal leisure days added to a business trip at the employee's cost.], [Governing chapter binds], 
  [Card slip], [A summary terminal receipt; not sufficient substantiation on its own.], [Governing chapter binds], 
  [City tax], [A mandatory municipal lodging levy, reimbursable in full.], [Governing chapter binds], 
  [Commercial invoice], [A vendor invoice for goods, governed by Chapter 10.], [Governing chapter binds], 
  [DoA], [Delegation of Authority; the approval tiers in Chapter 3.], [Governing chapter binds], 
  [Event surcharge cap], [A nightly lodging cap that replaces the tier cap in a named event week.], [Governing chapter binds], 
  [Folio], [An itemized hotel checkout bill.], [Governing chapter binds], 
  [Foreign VAT recovery], [The firm's reclaim of consumption tax on foreign business spend.], [Governing chapter binds], 
  [Garment rescue], [Spot cleaning of business attire on a stay of five nights or fewer.], [Governing chapter binds], 
  [Incidental], [A folio line other than the room rate; most are deducted.], [Governing chapter binds], 
  [PIR], [Property Irregularity Report; the airline record of a lost or delayed bag.], [Governing chapter binds], 
  [Pre-tip bill], [The bill total before a tip, used to compute the tip cap.], [Governing chapter binds], 
  [Reimbursable], [Eligible for repayment under the caps and conditions in this handbook.], [Governing chapter binds], 
  [Second class], [The standard rail cabin; reimbursable without further justification.], [Governing chapter binds], 
  [Solo dining], [One employee eating alone; governed by Chapter 7.], [Governing chapter binds], 
  [Staging greenery], [Temporary rented plants for a named, pre-approved event.], [Governing chapter binds], 
  [Superseded], [A schedule that applied to an earlier handbook version and is not current.], [Governing chapter binds], 
  [Tier], [A city's lodging cap band: Tier 1, Tier 2, or Tier 3.], [Governing chapter binds], 
  [Tip cap], [The maximum reimbursable gratuity, set by vendor country.], [Governing chapter binds], 
  [Truffle policy], [The Figure 3 screen applied before meal caps.], [Governing chapter binds], 
  [Unjustified ride], [A taxi or rideshare fare above the threshold without a stated justification.], [Governing chapter binds], 
  [VAT registration number], [A vendor tax identifier required on folios and commercial invoices.], [Governing chapter binds], 
)

== Reimbursement Calculation Order (Summary)

+ Confirm the receipt is itemized and complete.
+ Deduct non-reimbursable lines at their gross price, together with the tax on those lines.
+ Screen any truffle line under Figure 3.
+ Apply the relevant meal, lodging, or activity cap.
+ Apply the tip cap for the vendor country.
+ Reimburse the remainder, subject to the decision framework in Chapter 2.

== Reading the Schedules in Order

+ A named-event override in Chapter 9 beats the ordinary city tier.
+ A country row in Chapter 14 beats a regional tipping norm in Chapter 7.
+ A section of prose in Chapters 4 to 11 beats any orientation table in this chapter.
+ The historical schedules in Chapter 16 and the draft proposals in Chapter 17 are never effective for a current claim.
