#import "template.typ": card-do, card-dont

= Audit Findings and Common Misconceptions

Global Finance audits a rolling sample of claims each quarter. This chapter records the findings that recur and the misconceptions that cause them. Each row points to the chapter that actually governs.

#card-do("Use this chapter to self-review a claim")[
  Skim the misconception table before you submit. Finding a likely deduction yourself is faster than a query from the audit team.
]

== Common Audit Findings

#table(
  columns: (2.2fr, 1.6fr, 2.4fr, 1.4fr),
  align: (left, left, left, center),
  fill: (_, y) => if y == 0 { rgb("#dbeafe") } else if calc.even(y) { rgb("#f8fafc") } else { none },
  stroke: 0.5pt + rgb("#cbd5e1"),
  table.header[*Finding*][*Typical Cause*][*Resolution*][*Governing Reference*],
  [Missing vendor VAT registration number], [Vendor was not asked], [Reimburse net of VAT; coach the employee], [Chapter 12 governs], 
  [Summary card slip attached], [Original itemized bill lost], [Request the itemized bill; otherwise reject the line], [Chapter 2 governs], 
  [Unnamed rental vehicle on parking], [Note was brief], [Deduct the parking line], [Chapter 6 governs], 
  [Laundry without a soiling note], [Incident not described], [Deduct the laundry line], [Chapter 6 governs], 
  [Minibar item left on the folio], [Employee did not review the folio], [Deduct the incidental and its VAT], [Chapter 6 governs], 
  [Tip above the country cap], [Copying a home-country habit], [Deduct the excess], [Chapter 7 governs], 
  [Alcohol on a solo meal], [Receipt not trimmed], [Deduct each alcohol line], [Chapter 7 governs], 
  [Alcohol above the hospitality allowance], [Wine list guided by the host], [Deduct the excess proportionally], [Chapter 13 governs], 
  [Missing attendee count], [Note written from memory], [Evaluate as a solo meal], [Chapter 8 governs], 
  [Missing external organization], [Note written in a hurry], [Evaluate as a solo meal], [Chapter 8 governs], 
  [Weekend branch not evidenced], [Note omitted the facts], [Apply the non-reimbursable branch], [Chapter 13 governs], 
  [Event name absent for an event cap], [Employee assumed the city was enough], [Apply the ordinary city cap], [Chapter 9 governs], 
  [Truffle line not screened], [Reviewer skipped Figure 3], [Screen the line and adjust], [Chapter 13 governs], 
  [First class rail under four hours], [Ticket booked by a travel agent], [Deduct the fare], [Chapter 5 governs], 
  [Business class on a short segment], [Cabin chosen automatically], [Deduct the fare], [Chapter 4 governs], 
  [Premium rideshare tier], [App defaulted to premium], [Deduct the excess], [Chapter 5 governs], 
  [Rental above intermediate], [Only large cars available], [Request a named approver or deduct the excess], [Chapter 5 governs], 
  [Software bought out of pocket], [Urgent licence need], [Deduct the line; route to IT], [Chapter 10 governs], 
  [Peripheral without an IT ticket], [Purchase made on the road], [Deduct the line], [Chapter 10 governs], 
  [Gift card in an event invoice], [Bundled giveaways], [Deduct the gift card lines], [Chapter 11 governs], 
  [Personal charge on a corporate card], [Card mixing], [Deduct and flag for repayment], [Chapter 11 governs], 
  [Duplicate submission], [Portal retry], [Reject the duplicate], [Chapter 2 governs], 
  [Foreign receipt claimed in EUR], [Manual conversion], [Enter the printed currency], [Chapter 12 governs], 
  [Personal extension night claimed], [Trip extended privately], [Deduct the night], [Chapter 9 governs], 
  [Companion meal counted in the headcount], [Host added the guest], [Reduce the headcount and deduct the share], [Chapter 9 governs], 
  [Commuting fare claimed as a taxi], [Office trip after hours], [Deduct the fare], [Chapter 11 governs], 
  [Parking fine included in a garage receipt], [Fine paid at the machine], [Deduct the fine], [Chapter 11 governs], 
  [Lounge pass on a delayed flight], [Delay felt exceptional], [Deduct the pass], [Chapter 4 governs], 
  [Seat selection on a long-haul flight], [Comfort on an overnight], [Deduct the seat fee], [Chapter 4 governs], 
  [Non-itemized hotel rate], [Express checkout], [Request the folio; otherwise hold the claim], [Chapter 6 governs], 
  [City tax omitted from the claim], [Employee assumed it was included], [Add the city tax if itemized], [Chapter 6 governs], 
  [Daily aggregate exceeded], [Multiple small receipts], [Deduct the excess over the aggregate], [Chapter 7 governs], 
  [Overtime meal without a late-work note], [Takeaway at home], [Deduct the meal], [Chapter 7 governs], 
  [Candidate meal without a role], [Interview ran late], [Add the role or evaluate as a solo meal], [Chapter 8 governs], 
  [Theater tickets in a luxury tier], [Only premium seats left], [Deduct the excess over standard seating], [Chapter 8 governs], 
  [Invoice addressed to a client], [Vendor default billing], [Acceptable if the employee paid], [Chapter 10 governs], 
  [Mileage log lacking addresses], [Route remembered], [Request the addresses], [Chapter 5 governs], 
  [Fuel receipt without a vehicle], [Pool car unnamed], [Deduct the fuel line], [Chapter 5 governs], 
  [Baggage fee without a reason], [Extra suitcase], [Deduct unless business-necessary], [Chapter 4 governs], 
  [VAT number present but net not shown], [Invoice template], [Request a corrected invoice], [Chapter 12 governs], 
  [Dynamic currency conversion markup], [Terminal default], [Reimburse the local-currency amount only], [Chapter 12 governs], 
  [Expense older than thirty days], [Late submission], [Route for a waiver before processing], [Chapter 2 governs], 
  [Signature missing on a paper claim], [Digitization skipped], [Return for signature], [Chapter 2 governs], 
  [Approver outside the DoA tier], [Delegation not updated], [Escalate to the correct tier], [Chapter 3 governs], 
  [Event materials without a budget owner], [Pre-approval assumed], [Deduct the event material lines], [Chapter 10 governs], 
  [Booth greenery treated as furniture], [Reviewer applied the general exclusion], [Reclassify as staging greenery], [Chapter 10 governs], 
  [Office plant rental in an event invoice], [Mixed invoice], [Deduct the recurring plant line], [Chapter 10 governs], 
  [Streaming subscription on a travel card], [Personal account], [Deduct the line], [Chapter 11 governs], 
  [Medicine bought while traveling], [Headache tablets], [Deduct the line], [Chapter 11 governs], 
  [Clothing after a delayed bag], [Convenience purchase], [Require the PIR reference], [Chapter 11 governs], 
  [Foreign cash advance claimed], [Leftover currency], [Reject the item], [Chapter 12 governs], 
)

== Common Misconceptions

#table(
  columns: (2.4fr, 2.8fr, 1.4fr),
  align: (left, left, center),
  fill: (_, y) => if y == 0 { rgb("#dbeafe") } else if calc.even(y) { rgb("#f8fafc") } else { none },
  stroke: 0.5pt + rgb("#cbd5e1"),
  table.header[*Common Belief*][*Correct Position*][*Governing Reference*],
  [A suite is reimbursable if it is the only room left], [The nightly rate is capped by city tier regardless of room name.], [Chapter 6 governs], 
  [City tax counts against the nightly cap], [Mandatory city tax is reimbursed in full and sits outside the cap.], [Chapter 6 governs], 
  [The cap includes VAT added on top], [The cap applies to the room rate; VAT on the excess is deducted with it.], [Chapter 6 governs], 
  [Laundry is always reimbursable on a long stay], [It is capped per seven-day period and deducted above the cap.], [Chapter 6 governs], 
  [A short-stay laundry line is fine with a receipt], [It needs a note describing the soiling incident.], [Chapter 6 governs], 
  [Hotel parking is always covered], [It is capped per night and needs a named rental or pool vehicle.], [Chapter 6 governs], 
  [A loyalty upgrade changes the reimbursement], [The folio rate governs, not the room category booked or granted.], [Chapter 6 governs], 
  [Solo meals can include a glass of wine], [Alcohol during solo dining is deducted in full.], [Chapter 7 governs], 
  [A mocktail is treated as alcohol], [Non-alcoholic drinks are ordinary beverages.], [Chapter 7 governs], 
  [Unspent lunch allowance rolls into dinner], [Allowances do not roll over; the dinner cap is unchanged.], [Chapter 7 governs], 
  [Tips are reimbursed in full], [Tips are capped by the vendor country's norm.], [Chapter 7 governs], 
  [Takeaway tips are reimbursable in Europe], [Takeaway, counter, and delivery tips are not reimbursable in Europe.], [Chapter 7 governs], 
  [Truffle oil is only a flavour], [Truffle oil is screened under Figure 3.], [Chapter 13 governs], 
  [Caviar follows the truffle rule], [Caviar is governed by ordinary caps only.], [Chapter 7 governs], 
  [Any receipt dated on a weekend is rejected], [Weekend claims are evaluated under Figure 1.], [Chapter 13 governs], 
  [An early Monday meeting always covers a Sunday night], [Figure 1 governs the branch.], [Chapter 13 governs], 
  [A flight on a Saturday is a weekend expense], [Flights follow Chapters 4 and 5; lodging and meals on that day follow Figure 1.], [Chapter 9 governs], 
  [Bleisure nights are always covered], [Personal extension nights are the employee's cost.], [Chapter 9 governs], 
  [Companion meals split the cap], [Companions are excluded from the count and their share is deducted.], [Chapter 9 governs], 
  [A bigger room for a companion is covered], [Double-occupancy surcharges are deducted.], [Chapter 9 governs], 
  [Group meals without a note use the group caps], [A group bill lacking purpose or headcount is evaluated as a solo meal.], [Chapter 8 governs], 
  [Candidate meals are not hospitality], [Recruiting meals are client hospitality.], [Chapter 8 governs], 
  [Any client venue is acceptable], [Night clubs, casinos, and similar venues are rejected in full.], [Chapter 8 governs], 
  [VIP boxes are fine for client events], [Only standard seating tiers are reimbursable.], [Chapter 8 governs], 
  [Internal team meals are uncapped], [They follow the Figure 2 per-person cap.], [Chapter 13 governs], 
  [A taxi is covered whenever it is faster], [A fare above the threshold needs a stated justification.], [Chapter 5 governs], 
  [Rideshare premium tiers are covered], [The excess over the threshold is deducted.], [Chapter 5 governs], 
  [First class rail is always fine if it is cheaper], [First class is permitted only over four hours.], [Chapter 5 governs], 
  [A rental car upgrade is a small matter], [Above intermediate it needs a named approver.], [Chapter 5 governs], 
  [Commuting to the office is mileage], [Commuting is a personal expense.], [Chapter 11 governs], 
  [Parking fines can be claimed when unavoidable], [Fines and citations are always deducted.], [Chapter 11 governs], 
  [Business class is fine on any long flight], [It applies only when Chapter 4 permits it.], [Chapter 4 governs], 
  [Seat selection is a travel necessity], [Seat selection and extra legroom are deducted.], [Chapter 4 governs], 
  [Lounge access is reimbursable on late flights], [Lounge access is deducted.], [Chapter 4 governs], 
  [Government taxes can be excluded], [Mandatory taxes and surcharges are reimbursable in full.], [Chapter 4 governs], 
  [A change fee is always personal], [Business-necessary change fees are reimbursable.], [Chapter 4 governs], 
  [Software can be bought out of pocket], [Software is deducted; use the IT portal.], [Chapter 10 governs], 
  [Cloud credits are a routine expense], [Cloud credits are deducted.], [Chapter 10 governs], 
  [An external monitor is a normal peripheral], [It needs an IT ticket number at or above the threshold.], [Chapter 10 governs], 
  [Plants are reimbursable for a client event], [Only temporary staging greenery for a named, pre-approved event is.], [Chapter 10 governs], 
  [Office furniture is reimbursable with approval], [Furniture is deducted regardless of approval.], [Chapter 10 governs], 
  [Gift cards are a convenient thank-you], [Gift cards and vouchers are deducted.], [Chapter 11 governs], 
  [Personal clothing is covered if a bag is lost], [Only with a PIR reference and within the emergency cap.], [Chapter 11 governs], 
  [Sunscreen is a travel necessity], [Personal care items are deducted.], [Chapter 11 governs], 
  [Pet fees at a hotel are incidental], [Pet charges are deducted.], [Chapter 6 governs], 
  [Foreign cash can be bought back], [Unspent foreign currency is not reimbursable.], [Chapter 12 governs], 
  [Accepting card-terminal home currency is harmless], [The markup is not reimbursed; pay in local currency.], [Chapter 12 governs], 
  [A folio without a VAT number is rejected entirely], [It is reimbursed net of the VAT shown.], [Chapter 12 governs], 
  [A commercial invoice is exempt from VAT numbering], [It must show the vendor's VAT number.], [Chapter 12 governs], 
  [Restaurant receipts need a VAT number], [Restaurant, taxi, and fuel receipts are exempt from that requirement.], [Chapter 12 governs], 
  [Email approval is never acceptable], [Written pre-approval by email is acceptable where required.], [Chapter 3 governs], 
  [Verbal approval from a partner suffices], [Visual standards and written approvals govern.], [Chapter 8 governs], 
  [An event surcharge cap applies to the whole stay], [It applies only to nights inside the event window.], [Chapter 9 governs], 
  [Naming the event is optional], [The note must name the listed event for the override to apply.], [Chapter 9 governs], 
  [The prior year's rates still apply], [Version 4.2 governs claims processed from January 1, 2024.], [Chapter 16 governs], 
  [The draft 2025 rates are live], [Draft proposals are not effective.], [Chapter 17 governs], 
)

== Extended Questions and Answers

#table(
  columns: (2.8fr, 2.8fr, 1.4fr),
  align: (left, left, center),
  fill: (_, y) => if y == 0 { rgb("#dbeafe") } else if calc.even(y) { rgb("#f8fafc") } else { none },
  stroke: 0.5pt + rgb("#cbd5e1"),
  table.header[*Question*][*Short Answer*][*Governing Reference*],
  [Can I book a hotel outside the portal?], [Yes, but the same caps apply.], [Chapter 6 governs], 
  [Do I need to keep paper receipts?], [Electronic copies are accepted if legible and complete.], [Chapter 2 governs], 
  [What if the folio is several pages?], [Upload every page in sequence.], [Chapter 2 governs], 
  [Is breakfast at the hotel reimbursable?], [Up to the breakfast cap when itemized.], [Chapter 7 governs], 
  [Is a hotel restaurant dinner a meal?], [Yes, it counts toward the day's meal caps.], [Chapter 6 governs], 
  [Can I claim a hotel minibar water?], [No, minibar charges are deducted.], [Chapter 6 governs], 
  [Is the city tax capped?], [No, mandatory city tax is reimbursed in full.], [Chapter 6 governs], 
  [Can I keep loyalty points?], [Yes, keep the points; the folio rate still governs.], [Chapter 6 governs], 
  [Is valet parking reimbursable?], [It is capped per night with a named rental or pool vehicle.], [Chapter 6 governs], 
  [Can I launder a suit on a three-night stay?], [Only as a garment rescue with a soiling note.], [Chapter 6 governs], 
  [Is a coffee between meetings reimbursable?], [Yes, within the daily aggregate.], [Chapter 7 governs], 
  [Can I exceed one meal cap by underspending another?], [No, caps are not transferable.], [Chapter 7 governs], 
  [Are tips on takeaway reimbursable?], [Not in Europe.], [Chapter 7 governs], 
  [Is a service charge the same as a tip?], [A printed service charge is reimbursed; extra tip is capped.], [Chapter 7 governs], 
  [Does truffle oil trigger the flowchart?], [Yes, it is listed explicitly.], [Chapter 13 governs], 
  [Is caviar screened by Figure 3?], [No, ordinary caps govern.], [Chapter 7 governs], 
  [Can I host a client at a sporting event?], [Yes, in standard seating tiers.], [Chapter 8 governs], 
  [Can I host a client at a casino?], [No, the bill is rejected in full.], [Chapter 8 governs], 
  [Is a candidate meal client hospitality?], [Yes, state the role and candidates.], [Chapter 8 governs], 
  [What if the client orders expensive wine?], [The alcohol allowance still applies.], [Chapter 13 governs], 
  [Is a team dinner capped?], [Yes, per person under Figure 2.], [Chapter 13 governs], 
  [Does a team activity follow the meal cap?], [No, it has its own per-participant cap.], [Chapter 10 governs], 
  [Can I expense an escape room?], [Yes, within the team-building cap.], [Chapter 10 governs], 
  [Are booth giveaways reimbursable?], [Yes, for a named, pre-approved event.], [Chapter 10 governs], 
  [Are rubber ducks an event material?], [If bought for a named, pre-approved event.], [Chapter 10 governs], 
  [Can I buy a laptop out of pocket?], [No, IT issues laptops.], [Chapter 10 governs], 
  [Can I buy a monitor while traveling?], [Only with an IT ticket number.], [Chapter 10 governs], 
  [Is a subscription to a legal journal reimbursable?], [No, use the library service.], [Chapter 10 governs], 
  [Can I expense a book for a matter?], [Yes, up to the per-item cap with the matter cited.], [Chapter 10 governs], 
  [Is a courier of client documents reimbursable?], [Yes, state what was shipped.], [Chapter 10 governs], 
  [Is a travel eSIM reimbursable?], [Yes, up to the trip cap.], [Chapter 10 governs], 
  [Can I take a taxi instead of the train?], [Yes, but the fare threshold and justification apply.], [Chapter 5 governs], 
  [Is a premium rideshare reimbursable?], [Only up to the threshold.], [Chapter 5 governs], 
  [Is a first class rail ticket reimbursable?], [Only for journeys over four hours.], [Chapter 5 governs], 
  [Do I need a rental car justification?], [Yes, note the client sites served.], [Chapter 5 governs], 
  [Is a collision damage waiver reimbursable?], [Yes, when booked through the corporate channel.], [Chapter 5 governs], 
  [Can I claim mileage for commuting?], [No, commuting is personal.], [Chapter 11 governs], 
  [Are tolls and congestion charges reimbursable?], [Yes, with the receipt.], [Chapter 5 governs], 
  [Is a parking fine reimbursable?], [No, citations are always deducted.], [Chapter 11 governs], 
  [Can I fly business on a six-hour flight?], [Only if the segment meets the Chapter 4 conditions.], [Chapter 4 governs], 
  [Are government flight taxes reimbursable?], [Yes, in full.], [Chapter 4 governs], 
  [Is seat selection reimbursable?], [No.], [Chapter 4 governs], 
  [Is a lounge pass reimbursable?], [No.], [Chapter 4 governs], 
  [Can I claim a flight change fee?], [Yes, when business-necessary.], [Chapter 4 governs], 
  [Is a weekend hotel night covered?], [Follow Figure 1.], [Chapter 13 governs], 
  [Is a Sunday taxi covered?], [Follow Figure 1.], [Chapter 13 governs], 
  [Can I extend a trip for a holiday?], [Yes, at your own cost.], [Chapter 9 governs], 
  [Does my partner's meal count in the headcount?], [No, exclude companions and deduct their share.], [Chapter 9 governs], 
  [Is a rest day after a long flight covered?], [Weekday nights follow Chapter 6; weekend nights follow Figure 1.], [Chapter 9 governs], 
  [Do I use my home country's holidays?], [Use the destination country's holidays.], [Chapter 9 governs], 
  [Does an event cap cover the whole week?], [Only nights inside the event window.], [Chapter 9 governs], 
  [Can I claim a gift card for a client?], [No, gift cards are deducted.], [Chapter 11 governs], 
  [Is a hotel spa charge reimbursable?], [No.], [Chapter 6 governs], 
  [Is a gym day pass reimbursable?], [No.], [Chapter 11 governs], 
  [Is personal clothing reimbursable?], [Only after a lost bag with a PIR reference.], [Chapter 11 governs], 
  [Is sunscreen reimbursable?], [No.], [Chapter 11 governs], 
  [Is pet boarding reimbursable?], [No.], [Chapter 11 governs], 
  [Is childcare during travel reimbursable?], [No.], [Chapter 11 governs], 
  [Can I claim leftover foreign cash?], [No.], [Chapter 12 governs], 
  [Which currency do I claim?], [The currency printed on the receipt.], [Chapter 12 governs], 
  [Do I convert caps myself?], [No, Finance converts using the ECB rate.], [Chapter 12 governs], 
  [Is a folio without a VAT number rejected?], [No, it is reimbursed net of VAT.], [Chapter 12 governs], 
  [Do restaurant receipts need a VAT number?], [No.], [Chapter 12 governs], 
  [Is dynamic currency conversion reimbursable?], [The markup is not.], [Chapter 12 governs], 
  [Who approves an international flight?], [The Practice Leader in writing.], [Chapter 3 governs], 
  [Is email pre-approval valid?], [Yes, where written pre-approval is required.], [Chapter 3 governs], 
  [Can my manager approve above their tier?], [No, the DoA tier governs.], [Chapter 3 governs], 
  [How late can I submit a claim?], [Within thirty calendar days of transaction completion.], [Chapter 2 governs], 
  [What if I submit late?], [Request a waiver before processing.], [Chapter 2 governs], 
  [What if I lose a receipt?], [Provide a duplicate merchant copy where possible.], [Chapter 2 governs], 
  [Are card slips acceptable?], [Not as the sole proof of a business meal.], [Chapter 2 governs], 
  [Do I need the original folio?], [A complete electronic copy is acceptable.], [Chapter 2 governs], 
  [Are prior-year rates still valid?], [Version 4.2 governs claims processed from January 1, 2024.], [Chapter 16 governs], 
  [Are the 2025 draft rates live?], [No, drafts are not effective.], [Chapter 17 governs], 
  [Where is the current rate table?], [Chapters 6, 7, and 14 are authoritative.], [Chapter 14 governs], 
  [What is the order of precedence?], [Event override, then Chapter 14, then prose chapters, then orientation tables.], [Chapter 15 governs], 
)

== Escalation and Dispute Resolution

+ Raise the question with the Expense Auditing Team before resubmitting.
+ If the team and the employee still disagree, the claim is reviewed by the Head of Global Finance.
+ A final appeal may be made to the Audit Committee within thirty days.
+ The Audit Committee's written determination is recorded and becomes guidance for future claims.
